name: CI/CD Pipeline for Backend

on:
  push:
    branches:
      - main  # Only deploy on push to main branch
  pull_request:
    branches:
      - main  # Run tests on PR to main branch

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'  # Use your .NET version here

    - name: Restore Dependencies
      run: dotnet restore

    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal

    - name: Build the Project
      run: dotnet build --configuration Release

    - name: Publish the Project
      run: dotnet publish --configuration Release -o ${{env.DOTNET_ROOT}}/myapp  # Publish output path

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}\myapp  # Upload the published artifacts

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'  # Only run deploy on push to main

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: Backend-EPS3  # Your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{env.DOTNET_ROOT}}\myapp  # Path to the published artifact
