name: CI/CD Pipeline for Backend

on:
  push:
    branches:
      - main  # Only deploy on push to main branch
  pull_request:
    branches:
      - main  # Run tests on PR to main branch

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal

    - name: Build the Project
      run: dotnet publish -c Release -o ./out

  deploy:
    runs-on: windows-latest
    needs: build-and-test
    if: github.event_name == 'push'  # Only run deploy on push to main

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Backend-EPS3'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./out
