# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: TestAndMerge

on:
  pull_request:
    branches: 
      - "main"
      - "Development"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  merge-dev:
    if: github.event.pull_request.base.ref == 'dev' && success()
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Merge Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const { context, github } = require('@actions/github');
          const pr = context.payload.pull_request;
          if (!pr.mergeable) {
            core.setFailed("Merge conflict detected. Please resolve conflicts manually.");
          }
          if (pr && pr.state === "open") {
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number
            });
          }
